import fs from 'node:fs/promises';
import { foodsById } from '../src/data/foods';
const [id,source,reason]=process.argv.slice(2);
if(!foodsById[id]||!source||!reason)throw new Error('Usage: reject-generated-image <food-id> <source> <visual reason>');
const archive=`output/imagegen/rejected/${id}-${Date.now()}.png`;
await fs.mkdir('output/imagegen/rejected',{recursive:true});
await fs.copyFile(source,archive);
const file='docs/generated-image-review.json';
const review=JSON.parse(await fs.readFile(file,'utf8'));
review.rejected.push({id,file:archive,reason});
await fs.writeFile(file,JSON.stringify(review,null,2)+'\n');
console.log(`Rejected ${id}: original preserved.`);
